### PR TITLE
update remix plugin and other libs

### PR DESCRIPTION
**Pull request by bunsenstraat**
This might ensure the plugin to work in our new vscode implementation of remix.

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Woah! Thats a thing? do you have a link?

**Comment by bunsenstraat** [comment]
Hi, yes that's a thing, https://github.com/ethential/code-remix. It's an extension for vscode, still in alpha. But plugins will only work using the webview part of the remix plugin. So took the liberty of updating the code. It's basically the same. There are still some issues to deal with though.

**Comment by bunsenstraat** [comment]
any further thoughts on this? it'd be great if we'd be able to use this app in our vscode extension demo.

**Comment by pi0neerpat** [comment]
I'll look into this today. The API needs some work as well :)

**Comment by bunsenstraat** [comment]
Very cool!!!

**Pull request merged**
